### ISSUE TITLE
Fingerprint is not common, 8974 do not have it

### ISSUE THREAD

**Issue by rancidfrog** [sonyxperiadev/device-sony-common#84]
```
01-01 00:20:09.857  3941  3941 D SubSettings: Launching fragment com.android.settings.SecuritySettings
01-01 00:20:09.888  3941  3941 V SecuritySettings: No fingerprint hardware detected!!
01-01 00:20:09.897  3941  3941 D AndroidRuntime: Shutting down VM
01-01 00:20:09.899  3941  3941 E AndroidRuntime: FATAL EXCEPTION: main
01-01 00:20:09.899  3941  3941 E AndroidRuntime: Process: com.android.settings, PID: 3941
01-01 00:20:09.899  3941  3941 E AndroidRuntime: Theme: themes:{}
01-01 00:20:09.899  3941  3941 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.android.settings/com.android.settings.SubSettings}: java.lang.NullPointerException: Attempt to invoke interface method 'int android.security.IKeystoreService.is_hardware_backed(java.lang.String)' on a null object reference
01-01 00:20:09.899  3941  3941 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3131)
01-01 00:20:09.899  3941  3941 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3162)
01-01 00:20:09.899  3941  3941 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509)
01-01 00:20:09.899  3941  3941 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
01-01 00:20:09.899  3941  3941 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
01-01 00:20:09.899  3941  3941 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-01 00:20:09.899  3941  3941 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
01-01 00:20:09.899  3941  3941 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5458)
01-01 00:20:09.899  3941  3941 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-01 00:20:09.899  3941  3941 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-01 00:20:09.899  3941  3941 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
01-01 00:20:09.899  3941  3941 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int android.security.IKeystoreService.is_hardware_backed(java.lang.String)' on a null object reference
01-01 00:20:09.899  3941  3941 E AndroidRuntime: 	at android.security.KeyStore.isHardwareBacked(KeyStore.java:381)
01-01 00:20:09.899  3941  3941 E AndroidRuntime: 	at android.security.KeyStore.isHardwareBacked(KeyStore.java:376)
01-01 00:20:09.899  3941  3941 E AndroidRuntime: 	at com.android.settings.SecuritySettings.createPreferenceHierarchy(SecuritySettings.java:307)
01-01 00:20:09.899  3941  3941 E AndroidRuntime: 	at com.android.settings.SecuritySettings.onResume(SecuritySettings.java:630)
01-01 00:20:09.899  3941  3941 E AndroidRuntime: 	at android.app.Fragment.performResume(Fragment.java:2263)
01-01 00:20:09.899  3941  3941 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1008)
01-01 00:20:09.899  3941  3941 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
01-01 00:20:09.899  3941  3941 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1130)
01-01 00:20:09.899  3941  3941 E AndroidRuntime: 	at android.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:1963)
01-01 00:20:09.899  3941  3941 E AndroidRuntime: 	at android.app.FragmentController.dispatchResume(FragmentController.java:174)
01-01 00:20:09.899  3941  3941 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:6348)
01-01 00:20:09.899  3941  3941 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3120)
01-01 00:20:09.899  3941  3941 E AndroidRuntime: 	... 10 more
01-01 00:20:09.900  1196  2269 W ActivityManager:   Force finishing activity com.android.settings/.SubSettings
01-01 00:20:09.903  1196  2269 W ActivityManager:   Force finishing activity com.android.settings/.Settings
```

**Comment by jerpelea** [comment]
check Android.mk in the fingerprint folder
ifeq ($(filter-out satsuki sumire suzuran,$(TARGET_DEVICE)),)
